.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ellocash_qt test_ellocash_qt
clean: FORCE
	$(MAKE) -C .. ellocash_qt_clean test_ellocash_qt_clean
check: FORCE
	$(MAKE) -C .. test_ellocash_qt_check
ellocash-qt ellocash-qt.exe: FORCE
	 $(MAKE) -C .. ellocash_qt
